server:
  port: 9012

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  datasource:
    DriverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portfolioWatcher?allowPublicKeyRetrieval=true&useSSL=false
    username: hbstudent
    password: hbstudent
  application:
    name: stock-setter-service
  jpa:
    hibernate.dd-auto: update
    generate-ddl: true
    show-sql: true
