server:
  port: 9014

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  datasource:
    DriverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/portfolio_watcher?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ucantcme
  application:
    name: miscellaneous-homepage-service
  jpa:
    hibernate.dd-auto: update
    generate-ddl: true
    show-sql: true
