server:
  port: 8081


eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  zuul:
    routes:
      serviceA:
        path: /api/departments/**
        sensitiveHeaders: Authorization
        serviceId: department-service

security.enable-csrf: false